os: linux

language: python

jobs:
  include:
    - python: 3.8

install:
  # Install conda
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge
  - conda update conda

  # Install dependencies
  - conda create -n test --file requirements/run.txt
  - source activate test
  - conda remove --force regolith
  - pip install git+git://github.com/regro/regolith@master
  - python setup.py install

script:
  - set -e
  - conda install --file requirements/test.txt
  - coverage run run_tests.py
  - coverage report -m
  - codecov

notifications:
  email: false


